exports.data = [
  {
    placeId: 1,
    placeName: "Nagihan'ın Mutfağı",
    placeType: "Restoran",
    imgUrl:
      "https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=yKr1gOi3UN5fvyfWdrK52g&cb_client=search.gws-prod.gps&w=408&h=240&yaw=124.17311&pitch=0&thumbfov=100",
    latitude: 41.495301,
    longitude: 36.062553,
    description: [
      "Açık hava bölümü",
      "Temassız teslimat",
      "Adrese servis",
      "Paket servisi",
      "İçeride servis",
      "Tekerlekli sandalyeye uygun park yeri",
      "Kahvaltı",
      "Öğle yemeği",
      "Tatlı",
      "Oturma alanı",
    ],
  },
  {
    placeId: 2,
    placeName: "Gözde Cafe Bistro",
    placeType: "Restoran",
    latitude: 41.4947735,
    imgUrl:
      "https://lh5.googleusercontent.com/p/AF1QipOpmUNQXH-qDPouJG5cuLGrSsRmDzD8V2lbBOcM=w408-h408-k-no",
    longitude: 36.0767089,
    description: [
      "Açık hava bölümü",
      "Temassız teslimat",
      "Adrese servis",
      "Paket servisi",
      "İçeride servis",
      "Tekerlekli sandalyeye uygun park yeri",
      "Kahvaltı",
      "Öğle yemeği",
      "Tatlı",
      "Oturma alanı",
      "Canlı müzik",
      "Vejetaryenlere yönelik seçenekler",
    ],
  },
  {
    placeId: 3,
    placeName: "Saray Lokantası",
    placeType: "Restoran",
    imgUrl:
      "https://lh5.googleusercontent.com/p/AF1QipNdla31_eJhPF91QiabL0o2CEI9mwNlHE7B9bBH=w408-h306-k-no",
    latitude: 41.4926192,
    longitude: 36.0694476,
    description: [
      "Açık hava bölümü",
      "Temassız teslimat",
      "Adrese servis",
      "Paket servisi",
      "İçeride servis",
      "Tekerlekli sandalyeye uygun park yeri",
      "Kahvaltı",
      "Öğle yemeği",
      "Tatlı",
      "Oturma alanı",
      "Canlı müzik",
      "Vejetaryenlere yönelik seçenekler",
    ],
  },
  {
    placeId: 4,
    placeName: "Ballıca Pide Kebap",
    placeType: "Restoran",
    imgUrl:
      "https://lh5.googleusercontent.com/p/AF1QipMtKZVMNmAN5RHeUsAnGK7xs6DPvJaYDkUeHLaX=w408-h725-k-no",
    latitude: 41.4926192,
    longitude: 36.0694476,
    description: [
      "Açık hava bölümü",
      "Temassız teslimat",
      "Adrese servis",
      "Paket servisi",
      "İçeride servis",
      "Tekerlekli sandalyeye uygun park yeri",
      "Kahvaltı",
      "Öğle yemeği",
      "Tatlı",
      "Oturma alanı",
      "Canlı müzik",
      "Vejetaryenlere yönelik seçenekler",
    ],
  },
  {
    placeId: 5,
    placeName: "Kızılırmak Butik Otel",
    placeType: "Restoran",
    imgUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2CMrMp-fiY3PRGejzaqravsK1I_2mRbYyKQ&s",
    latitude: 41.5131983,
    longitude: 36.1143733,
    description: [" Çamaşır yıkama hizmeti"],
  },
  {
    placeId: 6,
    placeName: "Sarıgazel Tabiat Parkı",
    placeType: "Park",
    imgUrl:
      "https://lh5.googleusercontent.com/p/AF1QipOSm1b6pX14OOnPjt_lXyH7IS4tjpQufoSzGuj5=w408-h272-k-no",
    latitude: 41.5044957,
    longitude: 35.7365513,
    description: [
      "Tekerlekli sandalyeye uygun giriş",
      "Tekerlekli sandalyeye uygun park yeri",
      "Doğa yürüyüşü",
      "Barbekü ızgarası",
      "Basketbol sahası",
      "Piknik masaları",
      "Salıncaklar",
      "Umumi tuvalet",
      "Çocuk parkı",
      "Çocuklar için uygun",
      "Çocuklara uygun doğa yürüyüşleri",
    ],
  },
  {
    placeId: 7,
    placeName: "Kızılırmak Deltası Kuş Cenneti",
    placeType: "Park",
    imgUrl:
      "https://lh5.googleusercontent.com/p/AF1QipO6TSgovKn4E_u7rL9dbUEI-abwVt9GhbOsyFyZ=w426-h240-k-no",
    latitude: 41.5900586,
    longitude: 35.8876133,
    description: [
      "Tekerlekli sandalyeye uygun giriş",
      "Tekerlekli sandalyeye uygun park yeri",
      "Doğa yürüyüşü",
      "Umumi tuvalet",
      "Çocuklar için uygun",
      "Çocuklara uygun doğa yürüyüşleri",
    ],
  },
  {
    placeId: 8,
    placeName: "Albayrak Optik",
    placeType: "Optik",
    imgUrl:
      "https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=uU6pht-lCeVxFO2jEjRtZQ&cb_client=search.gws-prod.gps&w=408&h=240&yaw=180.46576&pitch=0&thumbfov=100",
    latitude: 41.5671494,
    longitude: 35.9018092,
    description: ["Adrese servis", "Aynı gün teslimat", "Kredi kartı"],
  },
  {
    placeId: 9,
    placeName: "Meydan Lokantası",
    placeType: "Restoran",
    imgUrl:
      "https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=gS4UpoE3O_dn_8Nlfsuw5Q&cb_client=search.gws-prod.gps&w=408&h=240&yaw=345.90277&pitch=0&thumbfov=100",
    latitude: 41.5671056,
    longitude: 35.9021394,
    description: ["Helal gıda ürünleri", "Öğle yemeği", "Tuvalet"],
  },
  {
    placeId: 10,
    placeName: "Celal Usta Bafra Tandır",
    placeType: "Restoran",
    imgUrl:
      "https://lh5.googleusercontent.com/p/AF1QipMcb8YpuHj8Y1Wk07shAmrSj0O5CtZZ7LccH0be=w426-h240-k-no",
    latitude: 41.5672195,
    longitude: 35.9026529,
    description: [
      "Tekerlekli sandalyeye uygun giriş",
      "Tekerlekli sandalyeye uygun park yeri",
      "Temassız teslimat",
      "Adrese servis",
      "Paket servisi",
      "İçeride servis",
      "Helal gıda ürünleri",
      "Kahvaltı",
      "Öğle yemeği",
      "Akşam yemeği",
      "Oturma alanı",
      "Tuvalet",
      "Banka kartı",
      "Çek",
      "Kredi kartı",
      "Çocuklar için uygun",
      "Mama sandalyesi",
    ],
  },
  {
    placeId: 11,
    placeName: "Sevgi Otel",
    placeType: "Otel",
    imgUrl:
      "https://lh5.googleusercontent.com/p/AF1QipPXD8tktyHMlpEW6AcqW3L9MVsWKO2paz6v7AlM=w408-h544-k-no",
    latitude: 41.5667711,
    longitude: 35.9011264,
    description: [
      "Ücretsiz kablosuz bağlantı",
      "Ücretsiz park alanı",
      "Çamaşır yıkama hizmeti",
      "Çocuklar için uygun",
    ],
  },
  {
    placeId: 12,
    placeName: "Bafra Müzesi",
    placeType: "Müze",
    imgUrl:
      "https://lh5.googleusercontent.com/p/AF1QipNQr7bGEtj6VZpeDHlMZxy01WrJXNfG4H6RCIwe=w408-h306-k-no",
    latitude: 41.5667711,
    longitude: 35.9011264,
    description: ["Tuvalet", "Çocuklar için uygun"],
  },
  {
    placeId: 13,
    placeName: "Duru Veteriner",
    placeType: "Veteriner",
    imgUrl:
      "https://lh5.googleusercontent.com/p/AF1QipO0rkPXUhSY0DgMwMGj11ruGZ5UjhLEBjzY6y1q=w408-h254-k-no",
    latitude: 41.5676636,
    longitude: 35.9055667,
    description: [
      "Tekerlekli sandalyeye uygun giriş",
      "Tekerlekli sandalyeye uygun park yeri",
      "Tuvalet",
      "Çocuklar için uygun",
      "Randevu gerekli",
    ],
  },
  {
    placeId: 14,
    placeName: "Kaan Çiçekçilik",
    placeType: "Çiçekçi",
    imgUrl:
      "https://lh5.googleusercontent.com/p/AF1QipOaiuY8b8x3vkpRUZ7SB0X_jELoTO5L8JUs_RIS=w408-h402-k-no",
    latitude: 41.5676403,
    longitude: 35.9046212,
    description: [
      "Adrese servis",
      "Mağazadan teslim alma",
      "Mağaza içinde alışveriş",
      "Aynı gün teslimat",
      "Banka kartı",
      "Kredi kartı",
    ],
  },
  {
    placeId: 15,
    placeName: "Bafra Tütün Müzesi",
    placeType: "Müze",
    imgUrl:
      "https://lh5.googleusercontent.com/p/AF1QipNfa04Gr_IJ0yF4xHPNAKFOJEfApFkirHj7gZo=w408-h544-k-no",
    latitude: 41.5638431,
    longitude: 35.8975871,
    description: [
      "Tekerlekli sandalyeye uygun giriş",
      "Tekerlekli sandalyeye uygun park yeri",
      "Çocuklar için uygun",
    ],
  },
  {
    placeId: 16,
    placeName: "NoraPark AVM",
    placeType: "AVM",
    imgUrl:
      "https://lh5.googleusercontent.com/p/AF1QipMhEe3eYaf5pPch-PhwBk5v0mPo-FwLZXDMV5XA=w426-h240-k-no",
    latitude: 41.5575697,
    longitude: 35.9096264,
    description: [
      "Tekerlekli sandalyeye uygun giriş",
      "Tekerlekli sandalyeye uygun park yeri",
      "Tekerlekli sandalyeye uygun tuvalet",
      "Mağaza içinde alışveriş",
      "Atari oyunları",
      "Tuvalet",
      "Çocuk parkı",
    ],
  },

  {
    placeId: 18,
    placeName: "Yasemin Eczanesi",
    placeType: "Eczane",
    imgUrl: "Alparslan Türkeş Parkı",
    latitude: 41.5596343,
    longitude: 35.9084926,
    description: ["Aynı gün teslimat", "Kredi kartı"],
  },
  {
    placeId: 19,
    placeName: "Yaşam Eczanesi",
    placeType: "Eczane",
    imgUrl:
      "https://lh5.googleusercontent.com/p/AF1QipMKZAALxwYONJYhCxnZ-IJA3HKvMrOqN2DnP19C=w408-h306-k-no",
    latitude: 41.5593486,
    longitude: 35.9033207,
    description: [
      "Arabaya teslim alma",
      "Adrese servis",
      "Arabaya servis",
      "Mağaza içinde alışveriş",
      "Aynı gün teslimat",
    ],
  },
  {
    placeId: 20,
    placeName: "çilem pastane cafe irfan usta",
    placeType: "Cafe",
    imgUrl:
      "https://lh5.googleusercontent.com/p/AF1QipMpx_TBcItFU_Yhq43xHSgn1n_MRfccK6lSVYrl=w408-h306-k-no",
    latitude: 41.4943733,
    longitude: 36.0797884,
    description: [
      "Tekerlekli sandalyeye uygun giriş",
      "Tekerlekli sandalyeye uygun park yeri",
      "Temassız teslimat",
      "Adrese servis",
      "Paket servisi",
      "Aynı gün teslimat",
      "Tatlı",
      "Tuvalet",
      "Kredi kartı",
    ],
  },
  {
    placeId: 21,
    placeName: "No.25 Café & Restaurant",
    placeType: "Restoran",
    imgUrl:
      "https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=-CPgEx-_XDv-Hk9WnWFiHQ&cb_client=search.gws-prod.gps&w=408&h=240&yaw=321.68134&pitch=0&thumbfov=100",
    latitude: 41.5026802,
    longitude: 36.113124,
    description: [
      "Tekerlekli sandalyeye uygun giriş",
      "Tekerlekli sandalyeye uygun park yeri",
      "Tekerlekli sandalyeye uygun tuvalet",
      "Temassız teslimat",
      "Açık hava bölümü",
      "Adrese servis",
      "Paket servisi",
      "Arabaya servis",
      "Aynı gün teslimat",
      "İçeride servis",
      "Helal gıda ürünleri",
      "Kahvaltı",
      "Öğle yemeği",
      "Akşam yemeği",
      "Kahve",
      "Oturma alanı",
      "Tuvalet",
      "Çocuklar için uygun",
    ],
  },
  {
    placeId: 22,
    placeName: "Samsun Atakum Bungalov Evleri",
    placeType: "Otel",
    imgUrl:
      "https://lh5.googleusercontent.com/p/AF1QipOYt93ggEc46aRClK2gbSZ0KyQKIr-Yixat-9qA=w408-h271-k-no",
    latitude: 41.4284684,
    longitude: 36.1595644,
    description: [],
  },
];
